# Generated by Django 3.2.11 on 2022-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='温度')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': '入寺登记表',
                'verbose_name_plural': '入寺登记表',
                'db_table': 'Staff',
            },
        ),
    ]
