# Generated by Django 3.2.11 on 2022-01-27 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='staff',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
