# Generated by Django 3.2.11 on 2022-01-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220127_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
