# Generated by Django 3.2.10 on 2022-01-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_staff_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入寺时间'),
        ),
    ]
